import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// UI
import Footer from "@/components/Footer";
import TailwindNav from "@/components/TailwindNav";

// Sanity
import { client } from "../sanity/lib/client";
import { NAVBAR_QUERY } from "../sanity/lib/queries";
import { NAVBAR_QUERYResult } from "@/sanity.types";
const options = { next: { revalidate: 30 } };

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Resilient LLC",
  description: "Generated by Josh Worden",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data: NAVBAR_QUERYResult = await client.fetch(
    NAVBAR_QUERY,
    {},
    options
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TailwindNav services={data} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
